### ISSUE TITLE
训练显存

### ISSUE THREAD

**Issue by xyzhang16** [EAP-Net/EAP-Net#2]
你好，我看您用了两个预训练模型，一个resnet、一个seresnet，请问您的显存开销大概是多少啊？

**Comment by EAP-Net** [comment]
您好，我们用的是resnet的backbone，关于seresnet部分是不参与训练的。因此基于resnet50的backbone，我们训练需要2块1080ti，针对resnet101我们需要3块1080ti进行训练。当然您也可以调整图片尺寸或batch size，让模型用一块显卡训练。不过这在一定程度上会影响模型效果。
